apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: azuredisk-csi.community.tanzu.vmware.com
spec:
  displayName: "azuredisk-csi"
  longDescription: "azuredisk CSI provider"
  shortDescription: "azuredisk CSI provider"
  providerName: VMware
  maintainers:
    - name: ping xiao
  categories:
    - "container storage interface"
