apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/upstream
    contents:
      - path: .
        git:
          url: https://github.com/kubernetes-sigs/azuredisk-csi-driver.git
          ref: b30b29a
          tags: 
          - "v1.18.0"
        includePaths:
          - deploy/csi-azuredisk-node.yaml
          - deploy/rbac-csi-azuredisk-node.yaml
          - deploy/rbac-csi-azuredisk-controller.yaml
          - deploy/csi-azuredisk-driver.yaml
          - deploy/csi-azuredisk-controller.yaml
          - deploy/csi-azuredisk-node-windows.yaml
          - deploy/csi-azuredisk-controller.yaml
          - deploy/csi-azuredisk-scheduler-extender.yaml

